### PR TITLE
osal.c (Windows): Use absolute time instead of relative time.

### PR DESCRIPTION
**Pull request by Apollo3zehn**
Based on issue #53.

Currently - on Windows - the function `osal_gettimeofday` provides the number of ticks since system boot, so it is not the _time of day_. To initialize DC correctly and also to provide meaningful time values in all the error functions (like `ecx_mbxerror` and `ecx_SoEerror`), I would like to add extended functionality to `osal.c`:

For this PR I renamed `osal_gettimeofday` to `osal_getrelativetime` and added a new implementation for `osal_gettimeofday` to now provide the absolute time. It is not advisable to use the absolute time everywhere, because `GetSystemTimeAsFileTime` is slower than `QueryPerformanceCounter`. For relative measurements, `QueryPerformanceCounter` is still a good choice.

I did not include `GetSystemTimePreciseAsFileTime`, which delivers a much more precise time, because Windows 7 and lower do not support this API and I don't know how to make the calls between `GetSystemTimePreciseAsFileTime` and `GetSystemTimeAsFileTime` conditionally, depending on the OS version.

### CODE REVIEW

**Comment by nakarlsson** [comment]
I get the point about relative and absolute time, but what is the purpose of this PR? SOEM still use relative time internally as it should since performance is important. Are you planning to provide a second PR that introduce usage of absolute time usage internally when reporting errors?

If not I can't see the purpose since the user call would end up in the application that I persume don't use SOEM osal gettimeofday anyway.

**Comment by Apollo3zehn** [comment]
I initially thought absolute time is used everywhere, except Windows. Therefore, for this answer, I went through all ```osal.c``` implementations and found that ```osal_gettimeofday()``` is implemented incosistently accross list of supported OS. The following is an overview of the implementations: 

- [intime](https://github.com/OpenEtherCATsociety/SOEM/blob/master/osal/intime/osal.c#L25) - absolute time
- [linux](https://github.com/OpenEtherCATsociety/SOEM/blob/master/osal/linux/osal.c#L34) - relative time
- [rtems](https://github.com/OpenEtherCATsociety/SOEM/blob/master/osal/rtems/osal.c#L34) - relative time
- [erika](https://github.com/OpenEtherCATsociety/SOEM/blob/master/osal/erika/osal.c#L30-L33) - unclear (does ```osEE_x86_64_tsc_read()``` return absolute time or is it a simple counter in the processor?). If it is relative, why is the epoch added?
- [rtk](https://github.com/OpenEtherCATsociety/SOEM/blob/master/osal/rtk/osal.c#L52) - relative time
- [vxworks](https://github.com/OpenEtherCATsociety/SOEM/blob/master/osal/vxworks/osal.c#L87) - absolute time
- [win32](https://github.com/OpenEtherCATsociety/SOEM/blob/master/osal/win32/osal.c#L24) - relative time

As mentioned, I was expecting from the method name '```gettimeofday()```' that absolute time is used on all OS except Windows. Based on this, the purpose of this PR was to unify the implementations. But it seems that this is not easily accomplished due to the possiblity of live locks, if I get it right from the comment in the linux implementation.

In my opinion, using absolute time (or *real time*) make sense in two places: For DC initalization and for error messages. This PR provides both:

- [DC](https://github.com/OpenEtherCATsociety/SOEM/blob/master/soem/ethercatdc.c#L271) uses ```osal_current_time()``` which in turn calls into the new implementation of ```osal_gettimeofday()```
- [ecx_SoEerror](https://github.com/OpenEtherCATsociety/SOEM/blob/8832ef0f2fa09fb0b06acaca239b51263ca1878c/soem/ethercatsoe.c#L52) and other error functions also call ```osal_current_time()``` to get the time.

With this PR the call hierachy becomes:

**absolute:**
```ecx_SoEerror()``` -> ```osal_current_time()``` -> ```osal_gettimeofday()```
```ecx_mbxerror()``` -> ```osal_current_time()``` -> ```osal_gettimeofday()```
```ecx_SDOerror()``` -> ```osal_current_time()``` -> ```osal_gettimeofday()```

```ecx_configdc()``` -> ```osal_current_time()``` -> ```osal_gettimeofday()``` 

**relative:**
```<time critical method>``` -> ```osal_timer_start``` -> ```osal_getrelativetime()```
```<time critical method>``` -> ```osal_timer_is_expired```  -> ```osal_getrelativetime()```

You can see from the overview that the time critical methods (```osal_timer_start()``` and ```osal_timer_is_expired()```) now call into ```osal_getrelativetime()```. **So there is no impact in time critical sections.**

To answer your questions more compact:

#### What is the purpose of this PR?
- My personal motivation behind this is to use DC time as source for measurement data timestamps (see also #287). For this, absolute time is useful. 
- SOEM errors should provide absolute time.
- I think a method called 'gettimeofday' should return the time of the day (instead of a random number).
- The document [Hardware Data Sheet Section I - Technology](https://download.beckhoff.com/download/document/io/ethercat-development-products/ethercat_esc_datasheet_sec1_technology_2i2.pdf) provides a definition of the system time (e.g. epoch start at 01.01.2000) and I think it is advantageous if all master implementations align with this definition.

#### Are you planning to provide a second PR that introduce usage of absolute time usage internally when reporting errors?
- In this PR, the above listed error functions already get the absolute time.

I do understand if you think this PR will introduce new inconsistencies with other OS's since they use either absolute **or** relative time. And with this PR only Windows uses both variants. But long term, I think the handling with absolute time should be unified on all OS implementations.

**Comment by nakarlsson** [comment]
Thanks for the analysis, it makes sense and I think aligning Win32 with Linux(eg PCs) when it comes to functionallity is a good thing. @ArthurKetels get final call since he did the Win32 port.
I mainly work with embedded systems and quite often don't have absolute time at all.

Please squash to a single commit.

**Comment by ArthurKetels** [comment]
I am happy to take the PR. And also from me, thanks for the analysis. I am fully aware of the unaligned implementations of time for the targets we support. SOEM itself is happy with any version of local time, as long it is fast and monotonous. The application however might be more interested in absolute time. 

But then I must complain about the utter garbage all OS have for absolute time. They are at best usable for file time stamps. But have nothing to do with control quality time keeping. 

For accurate measurements it is just as important to have precise time as having precise measurement values. A measurement is a vector, a measured quantity of interest at a moment in time. (and yes, this implies a clock as a quantity of interest).

Because our electronic hardware has no concept of time other than an arbitrary clock don't fool yourself you could have something like absolute time. It will only be a rough approximation.  Depending on your use case it could be acceptable but never the less an approximation. Other use cases might require much more accurate approximations. 

So in a way, all attempts to make an absolute time are still relative times. Then just as well stick with simple relative times and have some good estimator functions that can generate an acceptable guess  to what absolute time belongs a specific relative time stamp.

As an example a struct I use for accurate timing:

struct {
uint64  timestamp;
int  estimate_id;
uint64  estimate_sec;
uint64  estimate_femtosec;
double drift;
double drift_derrivative;
} timevector_t;

The estimate is to a reference clock with estimate_id. This also allows to transpose the timestamp from one reference clock to another. And at the same time keeping the original timestamp.

--end rant mode --

**Comment by Apollo3zehn** [comment]
Thanks @ArthurKetels for the explanation!

**Pull request merged**
