### PR TITLE
Fix linux osal timers and osal_current_time

### PR DESCRIPTION
**Pull request by alexkalmuk**
Fixes https://github.com/OpenEtherCATsociety/SOEM/issues/497

### CODE REVIEW

**Comment by nakarlsson** [comment]
Given the comments, why don't you use  clock_gettime(CLOCK_REALTIME , &ts); in osal_gettimeofday ?
Otherwise it make sense. What do you say @ArthurKetels?

We could make osal_gettimeofday/osal_getrelativetime "static"

**Comment by nakarlsson** [comment]
squash the commits, multiple commits are not relevant here

**Comment by alexkalmuk** [comment]
> squash the commits, multiple commits are not relevant here

Yes, of course. I just think it's a good practice to squash commits only after review to monitor new fixes.

**Comment by alexkalmuk** [comment]
squashed

**Comment by ArthurKetels** [comment]
@nakarlsson Yes I would prefer using clock_gettime(CLOCK_REALTIME , &ts); over gettimeofday(tv, tz);. It makes our intend more clear. We would not like to depend on internal implementation of gettimeofday() because it could change or have different semantics on different OS.

**Comment by nakarlsson** [comment]
@ArthurKetels and OK to re-introduce the real-time for DC time and Mbox communication? 
I believe the introduction of MONOTONIC time changed that, previously it was all gettimeofday.

**Comment by ArthurKetels** [comment]
As @alexkalmuk mentioned, gettimeofday is obsolete. Using REALTIME is the preferred option. The use cases for osal_current_time() are strictly for logging and start reference of DC. 

For DC we have no other option, we want to be as close as possible to wall clock time. We know we drift from that time after a while because we sync on slave reference time, but that is a whole other matter. The application can track the drift between realtime and DC time if it needs to. Another question is if we want time-zones? I would like to have machines running in UTC only, but customers might see that differently.

**Comment by alexkalmuk** [comment]
> Another question is if we want time-zones? I would like to have machines running in UTC only, but customers might see that differently.

BTW if timezones are required then `clock_gettime` probably can be used together with `localtime`/`localtime_r`.

**Comment by alexkalmuk** [comment]
Hm, as @nakarlsson mentioned about a potential change in DC behavior due to moving from MONOTONIC to REALTIME clock, shouldn't slave's System Time offset be changed each time in case of master's local time (REALTIME) was adjusted?

**Comment by nakarlsson** [comment]
I think the scope of this issue is covered by the current commit. @alexkalmuk do you agree? I'll merge the PR if so,

**Comment by alexkalmuk** [comment]
@nakarlsson Yes, of course. Thanks for your suggestions here and in the issue, they were very useful!

**Pull request merged**
