### PR TITLE
Proposal: Add Userdata to ecx_context

### PR DESCRIPTION
**Pull request by alex-brinkman**
This PR adds 4 improvements:
* Adds `void* userdata` to `ecx_context` 
* Adds CMake `VERSION`, `DESCIPTION`, `LANGUAGES` to `project()`
* Changes CMake print outs from `message(...)` to `message(STATUS ...)` 
* Improves `BUILD_TESTS` logic when building SOEM as a dependency

The `userdata` pointer is useful for accessing user contexts to PO2SO callbacks without global variables. This is especially important when using `EC_VER2` to support multiple ecx_contexts in a single process.

The CMake improvements mainly quality-of-life improvements. If you'd like me to break these improvements into different PRs or wish to revert some of my CMake improvements please be my guest!

### CODE REVIEW

**Comment by ntd** [comment]
I can confirm this can be helpful: I just met a test case where this would have solved my issue elegantly.

**Comment by nakarlsson** [comment]
Hi, it make sense to have a ref to the context application in a complex system. @ArthurKetels , any objections?

I'd like @hefloryd to check the Cmake stuff. Can you split the PR in? 
* userdata initialization to default ecx_contextt
* CMake stuff

**Comment by ArthurKetels** [comment]
The userdata pointer makes sense. When he CMake is checked, good to go for me.

**Comment by hefloryd** [comment]
Looks good to me!

**Comment by alex-brinkman** [comment]
It's a bit unclear to me, would you like me to split the PR or do these approvals indicate support for the PR as-is?

**Comment by nakarlsson** [comment]
no, skip the splitting since it is all here.

**Pull request merged**
