### PR TITLE
Make PDO CA access thread safe

### PR DESCRIPTION
**Pull request by nakarlsson**
Fix for #50

### CODE REVIEW

**Comment by hefloryd** [comment]
This commit changes the license text of the affected files (e.g. Eiserstraße to Eiserstrasse). Is that intentional? If we want to change the text we should probably change all files so they are identical wrt license, and do it in a separate commit.

**Comment by nakarlsson** [comment]
I did the change due to Eclipse prompting of issues about characters encoding, however you're right I shouldn't change them. I'll fix the pull request not to change the texts

**Comment by hefloryd** [comment]
In Eclipse you can set UTF-8 encoding as default by going to Window -> Preferences -> Workspace -> Text file encoding.

We could also add a BOM marker to the files. However, that could theoretically cause problems with some compilers.

Also I wouldn't be opposed to changing the license text to ASCII encoding.

**Comment by nakarlsson** [comment]
I reverted the licese change in a new commit, didn't figure out of to undo specific lines only.

**Pull request merged**
