### PR TITLE
Improve tutorial and documentation

### PR DESCRIPTION
**Pull request by alberth**
Small clarifications, mostly in tutorial

### CODE REVIEW

**Comment by alberth** [comment]
Fixed ec_config_map code, now checks for <= rather than >, which is confusing

**Comment by nakarlsson** [comment]
Please squash your commits into one

**Comment by alberth** [comment]
Squashed

**Comment by nakarlsson** [comment]
Thanks, it might take some time to find an open window to review the PR, but don't worry we're on it.

**Comment by nakarlsson** [comment]
Looks good, thank you for the constribution

**Pull request merged**
