### PR TITLE
Fixed grouping problem.

### PR DESCRIPTION
**Pull request by BauchBeinePoe**
Fixed issue #37.

### CODE REVIEW

**Comment by nakarlsson** [comment]
I think this fix also should remove the reset made in ecx_send_processdata_group.

**Comment by BauchBeinePoe** [comment]
Wouldn't that lead to fault behaviour if there are unhandled requests on the stack?

**Comment by nakarlsson** [comment]
Can you describe that use-case?  I might be missing something.

**Comment by BauchBeinePoe** [comment]
I guess since there is a timeout on the receive method every request is handled eventually so I was wrong, Removing the reset in the ecx_send_processdata_group should work. But I am curious why this reset is only made when the groupid is zero?

**Comment by nakarlsson** [comment]
There are use-cases when you want to be able to send multiple ecx_send_processdata_group sequentially before ecx_receive_processdata_group, groups being one. I think there are use-cases that also applies to group 0 hence my suggestion to remove the unconditional reset for group 0.

I believe the reset can  be unconditional in ecx_receive_processdata_group since we for sure exit the while on the empty stack criteria, but I want @ArthurKetels opinion before we proceed.

**Comment by ArthurKetels** [comment]
The change can be made unconditional. For now this is a satisfactory solution. Later I want to change ecx_receive_processdata_group() because the group argument can be removed if I add another parameter in ecx_pushindex() to flag a DC packet (indicated now with .hasdc and first). This is cleaner and solves the hackish parsing of the packet stack.

Grouped process data handling would then become:
for( i = STARTGROUP ; i <= ENDGROUP ; i++)
{
   ecx_send_processdata_group(.....);
}
.....
ecx_receive_processdata_group(.....);

Multiple send and only one receive to clean up the returned packet stack.

For good measure adding a ecx_clearindex() to reset the stack array to zero. It will make the intend more explicit.

**Comment by BauchBeinePoe** [comment]
Where can one obtain the working counter for each group then?

**Comment by nakarlsson** [comment]
Current design force you to handle every group explicitly (see below), the original use-case we had in mind was groups running with different update rate, in that case it don't matter. 

for( i = STARTGROUP ; i <= ENDGROUP ; i++)
 {
 ecx_send_processdata_group(.....);
 ecx_receive_processdata_group(.....);
 }

**Comment by ArthurKetels** [comment]
> Where can one obtain the working counter for each group then?
That is also data that needs to be pushed on the stack, so we can attribute the WCK to the correct group. ecx_receive_processdata_group() will return the total WCK of all packets processed. The group structure wil hold the latest WCK of its own group. ecx_send_processdata_group() resets its group WKC.

This way we do not break old code that relies on current behaviour.

**Pull request merged**
